In [3]:
import os
from datetime import datetime, timedelta
import numpy as np
import pandas as pd

In [4]:
DATA_URL_CONFIRMED = 'https://raw.githubusercontent.com/andrab/ecuacovid/master/datos_crudos/positivas/por_fecha/provincias_por_dia.csv'
DATA_URL_DEATHS = 'https://raw.githubusercontent.com/andrab/ecuacovid/master/datos_crudos/muertes/por_fecha/provincias_por_dia.csv'
DATA_TEMPLATE_URL = 'https://raw.githubusercontent.com/DataScienceResearchPeru/covid-19_latinoamerica/master/latam_covid_19_data/templates/daily_report.csv'
PATH_CSV = "utils/scripts/data_collection/data/ecuador_temporal/"
PATH_DSRP_DAILY_REPORTS = 'latam_covid_19_data/daily_reports/'
LAST_UPDATE = datetime.today().isoformat()
DICT_PLACES = {'Azuay': 'EC-A',
               'Bolívar': 'EC-B',
               'Carchi': 'EC-F',
               'Cañar': 'EC-C',
               'Chimborazo': 'EC-H',
               'Cotopaxi': 'EC-X',
               'El Oro': 'EC-O',
               'Esmeraldas': 'EC-E',
               'Galápagos': 'EC-W',
               'Guayas': 'EC-G',
               'Imbabura': 'EC-I',
               'Loja': 'EC-L',
               'Los Ríos': 'EC-R',
               'Manabí': 'EC-M',
               'Morona Santiago': 'EC-S',
               'Napo': 'EC-N',
               'Orellana': 'EC-D',
               'Pastaza': 'EC-Y',
               'Pichincha': 'EC-P',
               'Santa Elena': 'EC-SE',
               'Sto. Domingo Tsáchilas': 'EC-SD',
               'Sucumbíos': 'EC-U',
               'Tungurahua': 'EC-T',
               'Zamora Chinchipe': 'EC-Z'}

In [5]:
df_confirmed=pd.read_csv(DATA_URL_CONFIRMED)
df_confirmed['ISO 3166-2 Code']=df_confirmed['provincia'].map(DICT_PLACES)
d='2021-05-14'
d_fix = datetime.strptime(d, '%Y-%m-%d')
d_fix = d_fix.strftime('%d/%m/%Y')
df_confirmed=df_confirmed[['ISO 3166-2 Code',d_fix]]
df_confirmed

   ISO 3166-2 Code  14/05/2021
0             EC-A          47
1             EC-B           5
2             EC-F          37
3             EC-C           4
4             EC-H          24
5             EC-X          32
6             EC-O          60
7             EC-E          20
8             EC-W           0
9             EC-G         128
10            EC-I         112
11            EC-L          25
12            EC-R          30
13            EC-M          39
14            EC-S          18
15            EC-N           1
16            EC-D           2
17            EC-Y           0
18            EC-P         558
19           EC-SE           7
20           EC-SD          19
21            EC-U          20
22            EC-T          30
23            EC-Z           1

In [6]:
df_deaths=pd.read_csv(DATA_URL_DEATHS)
df_deaths['ISO 3166-2 Code']=df_deaths['provincia'].map(DICT_PLACES)
d='2021-05-14'
d_fix = datetime.strptime(d, '%Y-%m-%d')
d_fix = d_fix.strftime('%d/%m/%Y')
df_deaths=df_deaths[['ISO 3166-2 Code',d_fix]]
df_deaths

   ISO 3166-2 Code  14/05/2021
0             EC-A           3
1             EC-B           0
2             EC-F           0
3             EC-C           0
4             EC-H           0
5             EC-X           1
6             EC-O           5
7             EC-E           4
8             EC-W           0
9             EC-G          24
10            EC-I           2
11            EC-L           0
12            EC-R           1
13            EC-M          18
14            EC-S           0
15            EC-N           1
16            EC-D           0
17            EC-Y           1
18            EC-P           3
19           EC-SE           1
20           EC-SD           0
21            EC-U           0
22            EC-T           0
23            EC-Z           0

In [7]:
df_template=pd.read_csv(DATA_TEMPLATE_URL)
df_template=df_template.fillna(0)
df_template['Confirmed']=df_template['Confirmed'].astype(int)
df_template['Deaths']=df_template['Deaths'].astype(int)
df_template['Recovered']=df_template['Recovered'].astype(int)
df_template['Last Update']=''
df_template.head()

,ISO 3166-2 Code,Country,Subdivision,Last Update,Confirmed,Deaths,Recovered
0,AR-B,Argentina,Buenos Aires,,0,0,0
1,AR-K,Argentina,Catamarca,,0,0,0
2,AR-H,Argentina,Chaco,,0,0,0
3,AR-U,Argentina,Chubut,,0,0,0
4,AR-C,Argentina,Ciudad Autonoma de Buenos Aires,,0,0,0

In [8]:
for country_region in df_confirmed['ISO 3166-2 Code']:
    value_confirmed=df_confirmed.loc[df_confirmed['ISO 3166-2 Code']==country_region,d_fix]
    df_template.loc[df_template['ISO 3166-2 Code']==country_region,'Confirmed']=int(value_confirmed)

    value_deaths=df_deaths.loc[df_deaths['ISO 3166-2 Code']==country_region,d_fix]
    df_template.loc[df_template['ISO 3166-2 Code']==country_region,'Deaths']=int(value_deaths)

In [11]:
df_ec=df_template[df_template['ISO 3166-2 Code'].str.contains('EC-')]
df_ec

,ISO 3166-2 Code,Country,Subdivision,Last Update,Confirmed,Deaths,Recovered
164,EC-A,Ecuador,Azuay,,47,3,0
165,EC-B,Ecuador,Bolivar,,5,0,0
166,EC-F,Ecuador,Canar,,37,0,0
167,EC-C,Ecuador,Carchi,,4,0,0
168,EC-H,Ecuador,Chimborazo,,24,0,0
169,EC-X,Ecuador,Cotopaxi,,32,1,0
170,EC-O,Ecuador,El Oro,,60,5,0
171,EC-E,Ecuador,Esmeraldas,,20,4,0
172,EC-W,Ecuador,Galapagos,,0,0,0
173,EC-G,Ecuador,Guayas,,128,24,0
174,EC-I,Ecuador,Imbabura,,112,2,0
175,EC-L,Ecuador,Loja,,25,0,0
176,EC-R,Ecuador,Los Rios,,30,1,0
177,EC-M,Ecuador,Manabi,,39,18,0
178,EC-S,Ecuador,Morona Santiago,,18,0,0
179,EC-N,Ecuador,Napo,,1,1,0
180,EC-D,Ecuador,Orellana,,2,0,0
181,EC-Y,Ecuador,Pastaza,,0,1,0
182,EC-P,Ecuador,Pichincha,,558,3,0
183,EC-SE,Ecuador,Santa Elena,,7,1,0
184,EC-SD,Ecuador,Santo Domingo de los Tsachilas,,19,0,0
185,EC-U,Ecuador,Sucumbios,,20,0,0
186,EC-T,Ecuador,Tungurahua,,30,0,0
187,EC-Z,Ecuador,Zamora-Chinchipe,,1,0,0

In [12]:
df2=pd.read_csv(DATA_TEMPLATE_URL)
df2=df2.fillna(0)
df2['Confirmed']=df_template['Confirmed'].astype(int)
df2['Deaths']=df_template['Deaths'].astype(int)
df2['Recovered']=df_template['Recovered'].astype(int)
df2['Last Update']=''
df2.head()

,ISO 3166-2 Code,Country,Subdivision,Last Update,Confirmed,Deaths,Recovered
0,AR-B,Argentina,Buenos Aires,,0,0,0
1,AR-K,Argentina,Catamarca,,0,0,0
2,AR-H,Argentina,Chaco,,0,0,0
3,AR-U,Argentina,Chubut,,0,0,0
4,AR-C,Argentina,Ciudad Autonoma de Buenos Aires,,0,0,0

In [14]:
df2.combine_first(df_ec)
df2[df2['ISO 3166-2 Code'].str.contains('EC-')]

,ISO 3166-2 Code,Country,Subdivision,Last Update,Confirmed,Deaths,Recovered
164,EC-A,Ecuador,Azuay,,47,3,0
165,EC-B,Ecuador,Bolivar,,5,0,0
166,EC-F,Ecuador,Canar,,37,0,0
167,EC-C,Ecuador,Carchi,,4,0,0
168,EC-H,Ecuador,Chimborazo,,24,0,0
169,EC-X,Ecuador,Cotopaxi,,32,1,0
170,EC-O,Ecuador,El Oro,,60,5,0
171,EC-E,Ecuador,Esmeraldas,,20,4,0
172,EC-W,Ecuador,Galapagos,,0,0,0
173,EC-G,Ecuador,Guayas,,128,24,0
174,EC-I,Ecuador,Imbabura,,112,2,0
175,EC-L,Ecuador,Loja,,25,0,0
176,EC-R,Ecuador,Los Rios,,30,1,0
177,EC-M,Ecuador,Manabi,,39,18,0
178,EC-S,Ecuador,Morona Santiago,,18,0,0
179,EC-N,Ecuador,Napo,,1,1,0
180,EC-D,Ecuador,Orellana,,2,0,0
181,EC-Y,Ecuador,Pastaza,,0,1,0
182,EC-P,Ecuador,Pichincha,,558,3,0
183,EC-SE,Ecuador,Santa Elena,,7,1,0
184,EC-SD,Ecuador,Santo Domingo de los Tsachilas,,19,0,0
185,EC-U,Ecuador,Sucumbios,,20,0,0
186,EC-T,Ecuador,Tungurahua,,30,0,0
187,EC-Z,Ecuador,Zamora-Chinchipe,,1,0,0