In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/jmcastagnetto/covid-19-peru-data/main/datos/covid-19-peru-data.csv')

df['date']=pd.to_datetime(df['date']).dt.strftime('%Y-%m-%dT%H:%M%:%SZ')

In [3]:
df.head()

,country,iso3c,region,date,confirmed,deaths,recovered,total_tests,negative_tests,pcr_test_positive,serological_test_positive,ag_test_positive,pcr_serological_test_positive
0,Peru,PER,NaN,2020-03-06 00:00:00,1.0,NaN,NaN,NaN,154.0,NaN,NaN,NaN,NaN
1,Peru,PER,NaN,2020-03-07 00:00:00,6.0,NaN,NaN,NaN,213.0,NaN,NaN,NaN,NaN
2,Peru,PER,NaN,2020-03-09 00:00:00,9.0,NaN,NaN,NaN,309.0,NaN,NaN,NaN,NaN
3,Peru,PER,NaN,2020-03-10 00:00:00,11.0,NaN,NaN,NaN,335.0,NaN,NaN,NaN,NaN
4,Peru,PER,NaN,2020-03-11 00:00:00,17.0,NaN,NaN,NaN,697.0,NaN,NaN,NaN,NaN

In [5]:
df_filtered_by_day=df[df['date'].str.contains('2021-05-13')]
len(df_filtered_by_day)

27

In [6]:
df_filtered_by_day

,country,iso3c,region,date,confirmed,deaths,recovered,total_tests,negative_tests,pcr_test_positive,serological_test_positive,ag_test_positive,pcr_serological_test_positive
11147,Peru,PER,Amazonas,2021-05-13 00:00:00,27339.0,486.0,NaN,121734.0,94395.0,4370.0,18020.0,4949.0,NaN
11148,Peru,PER,Ancash,2021-05-13 00:00:00,66090.0,2824.0,NaN,364062.0,297972.0,14278.0,27349.0,24463.0,NaN
11149,Peru,PER,Apurimac,2021-05-13 00:00:00,21116.0,542.0,NaN,152497.0,131381.0,4781.0,8185.0,8150.0,NaN
11150,Peru,PER,Arequipa,2021-05-13 00:00:00,76480.0,2632.0,NaN,677340.0,600860.0,17141.0,46547.0,12792.0,NaN
11151,Peru,PER,Ayacucho,2021-05-13 00:00:00,27457.0,789.0,NaN,133642.0,106185.0,6225.0,14648.0,6584.0,NaN
11152,Peru,PER,Cajamarca,2021-05-13 00:00:00,54935.0,1367.0,NaN,315111.0,260176.0,12920.0,26891.0,15124.0,NaN
11153,Peru,PER,Callao,2021-05-13 00:00:00,93428.0,3345.0,NaN,540026.0,446598.0,43270.0,35784.0,14374.0,NaN
11154,Peru,PER,Cusco,2021-05-13 00:00:00,58130.0,1307.0,NaN,354989.0,296859.0,15518.0,23540.0,19072.0,NaN
11155,Peru,PER,Huancavelica,2021-05-13 00:00:00,13855.0,406.0,NaN,103691.0,89836.0,1849.0,7962.0,4044.0,NaN
11156,Peru,PER,Huánuco,2021-05-13 00:00:00,30858.0,1014.0,NaN,173359.0,142501.0,3518.0,20849.0,6491.0,NaN
11157,Peru,PER,Ica,2021-05-13 00:00:00,50364.0,2934.0,NaN,265160.0,214796.0,7536.0,31780.0,11048.0,NaN
11158,Peru,PER,Junín,2021-05-13 00:00:00,66645.0,2332.0,NaN,415835.0,349190.0,11243.0,38336.0,17066.0,NaN
11159,Peru,PER,La Libertad,2021-05-13 00:00:00,71524.0,3973.0,NaN,393580.0,322056.0,14610.0,36642.0,20272.0,NaN
11160,Peru,PER,Lambayeque,2021-05-13 00:00:00,52963.0,2631.0,NaN,286845.0,233882.0,11100.0,33257.0,8606.0,NaN
11161,Peru,PER,Lima Metropolitana,2021-05-13 00:00:00,792044.0,25569.0,NaN,5560558.0,4768514.0,340834.0,306456.0,144754.0,NaN
11162,Peru,PER,Lima Región,2021-05-13 00:00:00,63700.0,2925.0,NaN,360890.0,297190.0,12257.0,30395.0,21048.0,NaN
11163,Peru,PER,Loreto,2021-05-13 00:00:00,39127.0,1404.0,NaN,170782.0,131655.0,7321.0,26563.0,5243.0,NaN
11164,Peru,PER,Madre de Dios,2021-05-13 00:00:00,12887.0,234.0,NaN,70776.0,57889.0,1191.0,9615.0,2081.0,NaN
11165,Peru,PER,Moquegua,2021-05-13 00:00:00,23840.0,559.0,NaN,216518.0,192678.0,3791.0,17806.0,2243.0,NaN
11166,Peru,PER,Pasco,2021-05-13 00:00:00,13497.0,401.0,NaN,139281.0,125784.0,982.0,9004.0,3511.0,NaN
11167,Peru,PER,Piura,2021-05-13 00:00:00,73934.0,3154.0,NaN,353665.0,279731.0,5902.0,45178.0,22854.0,NaN
11168,Peru,PER,Puno,2021-05-13 00:00:00,30335.0,912.0,NaN,176107.0,145772.0,4581.0,20547.0,5207.0,NaN
11169,Peru,PER,San Martín,2021-05-13 00:00:00,42155.0,1252.0,NaN,191754.0,149599.0,7210.0,27116.0,7829.0,NaN
11170,Peru,PER,Tacna,2021-05-13 00:00:00,24110.0,785.0,NaN,154862.0,130752.0,3886.0,15400.0,4824.0,NaN
11171,Peru,PER,Tumbes,2021-05-13 00:00:00,15838.0,580.0,NaN,87390.0,71552.0,3552.0,8879.0,3407.0,NaN
11172,Peru,PER,Ucayali,2021-05-13 00:00:00,30665.0,959.0,NaN,121067.0,90402.0,2307.0,21740.0,6618.0,NaN
11173,Peru,PER,NaN,2021-05-13 00:00:00,1873316.0,65316.0,1818686.0,11901521.0,10028205.0,562173.0,908489.0,402654.0,NaN

In [7]:
df_filtered_by_day=df_filtered_by_day.fillna(0)
df_filtered_by_day['confirmed']=df_filtered_by_day['confirmed'].astype(int)
df_filtered_by_day['deaths']=df_filtered_by_day['deaths'].astype(int)
df_filtered_by_day['recovered']=df_filtered_by_day['recovered'].astype(int)
df_filtered_by_day=df_filtered_by_day[['region','date','confirmed','deaths','recovered']]
df_filtered_by_day.info()
df_filtered_by_day

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27 entries, 11147 to 11173
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   region     27 non-null     object
 1   date       27 non-null     object
 2   confirmed  27 non-null     int32
 3   deaths     27 non-null     int32
 4   recovered  27 non-null     int32
dtypes: int32(3), object(2)
memory usage: 972.0+ bytes

                   region                 date  confirmed  deaths  recovered
11147            Amazonas  2021-05-13 00:00:00      27339     486          0
11148              Ancash  2021-05-13 00:00:00      66090    2824          0
11149            Apurimac  2021-05-13 00:00:00      21116     542          0
11150            Arequipa  2021-05-13 00:00:00      76480    2632          0
11151            Ayacucho  2021-05-13 00:00:00      27457     789          0
11152           Cajamarca  2021-05-13 00:00:00      54935    1367          0
11153              Callao  2021-05-13 00:00:00      93428    3345          0
11154               Cusco  2021-05-13 00:00:00      58130    1307          0
11155        Huancavelica  2021-05-13 00:00:00      13855     406          0
11156             Huánuco  2021-05-13 00:00:00      30858    1014          0
11157                 Ica  2021-05-13 00:00:00      50364    2934          0
11158               Junín  2021-05-13 00:00:00      66645    2332          0
11159         La Libertad  2021-05-13 00:00:00      71524    3973          0
11160          Lambayeque  2021-05-13 00:00:00      52963    2631          0
11161  Lima Metropolitana  2021-05-13 00:00:00     792044   25569          0
11162         Lima Región  2021-05-13 00:00:00      63700    2925          0
11163              Loreto  2021-05-13 00:00:00      39127    1404          0
11164       Madre de Dios  2021-05-13 00:00:00      12887     234          0
11165            Moquegua  2021-05-13 00:00:00      23840     559          0
11166               Pasco  2021-05-13 00:00:00      13497     401          0
11167               Piura  2021-05-13 00:00:00      73934    3154          0
11168                Puno  2021-05-13 00:00:00      30335     912          0
11169          San Martín  2021-05-13 00:00:00      42155    1252          0
11170               Tacna  2021-05-13 00:00:00      24110     785          0
11171              Tumbes  2021-05-13 00:00:00      15838     580          0
11172             Ucayali  2021-05-13 00:00:00      30665     959          0
11173                   0  2021-05-13 00:00:00    1873316   65316    1818686

In [8]:
len(df)

11174

In [9]:
df_template=pd.read_csv('https://raw.githubusercontent.com/DataScienceResearchPeru/covid-19_latinoamerica/master/latam_covid_19_data/templates/daily_report.csv')
df_template=df_template.fillna(0)
df_template['Confirmed']=df_template['Confirmed'].astype(int)
df_template['Deaths']=df_template['Deaths'].astype(int)
df_template['Recovered']=df_template['Recovered'].astype(int)
df_template['Last Update']=''
df_template.head()

,ISO 3166-2 Code,Country,Subdivision,Last Update,Confirmed,Deaths,Recovered
0,AR-B,Argentina,Buenos Aires,0.0,0,0,0
1,AR-K,Argentina,Catamarca,0.0,0,0,0
2,AR-H,Argentina,Chaco,0.0,0,0,0
3,AR-U,Argentina,Chubut,0.0,0,0,0
4,AR-C,Argentina,Ciudad Autonoma de Buenos Aires,0.0,0,0,0

In [10]:
dict_places={'Amazonas':'PE-AMA',
'Ancash':'PE-ANC',
'Apurimac': 'PE-APU',
'Arequipa':'PE-ARE',
'Ayacucho':  'PE-AYA',
'Cajamarca': 'PE-CAJ',
'Callao': 'PE-CAL',
'Cusco':  'PE-CUS',
'Huancavelica':  'PE-HUV',
'Huánuco':   'PE-HUC',
'Ica': 'PE-ICA',
'Junín': 'PE-JUN',
'La Libertad':  'PE-LAL',
'Lambayeque': 'PE-LAM',
'Lima Metropolitana':'PE-LIM',
'Lima Región':'PE-LIM',
'Lima': 'PE-LIM',
'Loreto': 'PE-LOR',
'Madre de Dios': 'PE-MDD',
'Moquegua': 'PE-MOQ',
'Pasco':'PE-PAS',
'Piura':'PE-PIU',
'Puno':    'PE-PUN',
'San Martín':'PE-SAM',
'Tacna': 'PE-TAC',
'Tumbes': 'PE-TUM',
'Ucayali':  'PE-UCA'}

In [11]:
df_filtered_by_day['ISO 3166-2 Code']=df_filtered_by_day['region'].map(dict_places)DICT_PLACES
df_filtered_by_day

,region,date,confirmed,deaths,recovered,ISO 3166-2 Code
11147,Amazonas,2021-05-13 00:00:00,27339,486,0,PE-AMA
11148,Ancash,2021-05-13 00:00:00,66090,2824,0,PE-ANC
11149,Apurimac,2021-05-13 00:00:00,21116,542,0,PE-APU
11150,Arequipa,2021-05-13 00:00:00,76480,2632,0,PE-ARE
11151,Ayacucho,2021-05-13 00:00:00,27457,789,0,PE-AYA
11152,Cajamarca,2021-05-13 00:00:00,54935,1367,0,PE-CAJ
11153,Callao,2021-05-13 00:00:00,93428,3345,0,PE-CAL
11154,Cusco,2021-05-13 00:00:00,58130,1307,0,PE-CUS
11155,Huancavelica,2021-05-13 00:00:00,13855,406,0,PE-HUV
11156,Huánuco,2021-05-13 00:00:00,30858,1014,0,PE-HUC
11157,Ica,2021-05-13 00:00:00,50364,2934,0,PE-ICA
11158,Junín,2021-05-13 00:00:00,66645,2332,0,PE-JUN
11159,La Libertad,2021-05-13 00:00:00,71524,3973,0,PE-LAL
11160,Lambayeque,2021-05-13 00:00:00,52963,2631,0,PE-LAM
11161,Lima Metropolitana,2021-05-13 00:00:00,792044,25569,0,PE-LIM
11162,Lima Región,2021-05-13 00:00:00,63700,2925,0,PE-LIM
11163,Loreto,2021-05-13 00:00:00,39127,1404,0,PE-LOR
11164,Madre de Dios,2021-05-13 00:00:00,12887,234,0,PE-MDD
11165,Moquegua,2021-05-13 00:00:00,23840,559,0,PE-MOQ
11166,Pasco,2021-05-13 00:00:00,13497,401,0,PE-PAS
11167,Piura,2021-05-13 00:00:00,73934,3154,0,PE-PIU
11168,Puno,2021-05-13 00:00:00,30335,912,0,PE-PUN
11169,San Martín,2021-05-13 00:00:00,42155,1252,0,PE-SAM
11170,Tacna,2021-05-13 00:00:00,24110,785,0,PE-TAC
11171,Tumbes,2021-05-13 00:00:00,15838,580,0,PE-TUM
11172,Ucayali,2021-05-13 00:00:00,30665,959,0,PE-UCA
11173,0,2021-05-13 00:00:00,1873316,65316,1818686,NaN

In [12]:
# sum 'PE-LIM' exceptions
df_filtered_by_day=df_filtered_by_day.groupby('ISO 3166-2 Code').sum()
df_filtered_by_day

                 confirmed  deaths  recovered
ISO 3166-2 Code
PE-AMA               27339     486          0
PE-ANC               66090    2824          0
PE-APU               21116     542          0
PE-ARE               76480    2632          0
PE-AYA               27457     789          0
PE-CAJ               54935    1367          0
PE-CAL               93428    3345          0
PE-CUS               58130    1307          0
PE-HUC               30858    1014          0
PE-HUV               13855     406          0
PE-ICA               50364    2934          0
PE-JUN               66645    2332          0
PE-LAL               71524    3973          0
PE-LAM               52963    2631          0
PE-LIM              855744   28494          0
PE-LOR               39127    1404          0
PE-MDD               12887     234          0
PE-MOQ               23840     559          0
PE-PAS               13497     401          0
PE-PIU               73934    3154          0
PE-PUN               30335     912          0
PE-SAM               42155    1252          0
PE-TAC               24110     785          0
PE-TUM               15838     580          0
PE-UCA               30665     959          0

In [13]:
last_update=datetime.today().isoformat()
df_template['Last Update']=last_update
df_template=df_template[df_template['ISO 3166-2 Code'].str.contains('PE-')==True]

In [14]:
df_filtered_by_day

                 confirmed  deaths  recovered
ISO 3166-2 Code
PE-AMA               27339     486          0
PE-ANC               66090    2824          0
PE-APU               21116     542          0
PE-ARE               76480    2632          0
PE-AYA               27457     789          0
PE-CAJ               54935    1367          0
PE-CAL               93428    3345          0
PE-CUS               58130    1307          0
PE-HUC               30858    1014          0
PE-HUV               13855     406          0
PE-ICA               50364    2934          0
PE-JUN               66645    2332          0
PE-LAL               71524    3973          0
PE-LAM               52963    2631          0
PE-LIM              855744   28494          0
PE-LOR               39127    1404          0
PE-MDD               12887     234          0
PE-MOQ               23840     559          0
PE-PAS               13497     401          0
PE-PIU               73934    3154          0
PE-PUN               30335     912          0
PE-SAM               42155    1252          0
PE-TAC               24110     785          0
PE-TUM               15838     580          0
PE-UCA               30665     959          0

In [18]:

for country_region in df_filtered_by_day.index:
    # Confirmed
    value_confirmed=df_filtered_by_day.loc[df_filtered_by_day.index==country_region,'confirmed'].astype(int)
    df_template.loc[df_template['ISO 3166-2 Code']==country_region,'Confirmed']=int(value_confirmed)
    
    # Deaths    
    value_deaths=df_filtered_by_day.loc[df_filtered_by_day.index==country_region,'deaths'].astype(int)
    df_template.loc[df_template['ISO 3166-2 Code']==country_region,'Deaths']=int(value_deaths)
    
    # Recovered
    value_recovered=df_filtered_by_day.loc[df_filtered_by_day.index==country_region,'recovered'].astype(int)
    df_template.loc[df_template['ISO 3166-2 Code']==country_region,'Recovered']=int(value_recovered)


df_template

,ISO 3166-2 Code,Country,Subdivision,Last Update,Confirmed,Deaths,Recovered
338,PE-AMA,Peru,Amazonas,2021-05-14T21:18:51.326236,27339,486,0
339,PE-ANC,Peru,Ancash,2021-05-14T21:18:51.326236,66090,2824,0
340,PE-APU,Peru,Apurimac,2021-05-14T21:18:51.326236,21116,542,0
341,PE-ARE,Peru,Arequipa,2021-05-14T21:18:51.326236,76480,2632,0
342,PE-AYA,Peru,Ayacucho,2021-05-14T21:18:51.326236,27457,789,0
343,PE-CAJ,Peru,Cajamarca,2021-05-14T21:18:51.326236,54935,1367,0
344,PE-CAL,Peru,Callao,2021-05-14T21:18:51.326236,93428,3345,0
345,PE-CUS,Peru,Cusco,2021-05-14T21:18:51.326236,58130,1307,0
346,PE-HUV,Peru,Huancavelica,2021-05-14T21:18:51.326236,13855,406,0
347,PE-HUC,Peru,Huanuco,2021-05-14T21:18:51.326236,30858,1014,0
348,PE-ICA,Peru,Ica,2021-05-14T21:18:51.326236,50364,2934,0
349,PE-JUN,Peru,Junin,2021-05-14T21:18:51.326236,66645,2332,0
350,PE-LAL,Peru,La Libertad,2021-05-14T21:18:51.326236,71524,3973,0
351,PE-LAM,Peru,Lambayeque,2021-05-14T21:18:51.326236,52963,2631,0
352,PE-LIM,Peru,Lima,2021-05-14T21:18:51.326236,855744,28494,0
353,PE-LOR,Peru,Loreto,2021-05-14T21:18:51.326236,39127,1404,0
354,PE-MDD,Peru,Madre de dios,2021-05-14T21:18:51.326236,12887,234,0
355,PE-MOQ,Peru,Moquegua,2021-05-14T21:18:51.326236,23840,559,0
356,PE-PAS,Peru,Pasco,2021-05-14T21:18:51.326236,13497,401,0
357,PE-PIU,Peru,Piura,2021-05-14T21:18:51.326236,73934,3154,0
358,PE-PUN,Peru,Puno,2021-05-14T21:18:51.326236,30335,912,0
359,PE-SAM,Peru,San Martin,2021-05-14T21:18:51.326236,42155,1252,0
360,PE-TAC,Peru,Tacna,2021-05-14T21:18:51.326236,24110,785,0
361,PE-TUM,Peru,Tumbes,2021-05-14T21:18:51.326236,15838,580,0
362,PE-UCA,Peru,Ucayali,2021-05-14T21:18:51.326236,30665,959,0